version: '3'
services:
  database:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    container_name: 'sql-server-17'
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
